apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: topolvm
  namespace: topolvm-system
spec:
  chart:
    spec:
      chart: topolvm
      version: 15.x
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: topolvm
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: topolvm
  valuesFrom:
  - kind: ConfigMap
    name: topolvm-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity